
version: "3.9"

services:
  app1:
    build: .
    image: rand-line
    environment:
      SYMBOL: "#"
      MIN_LEN: 5
      MAX_LEN: 8
      DELAY: 1

  app2:
    image: rand-line
    environment:
      SYMBOL: "*"
      MIN_LEN: 8
      MAX_LEN: 12
      DELAY: 2

  app3:
    image: rand-line
    environment:
      SYMBOL: "+"
      MIN_LEN: 10
      MAX_LEN: 15
      DELAY: 3
